OOP版lsコマンド作成
MikotoMakizuru/ruby-practices pull request #11
Opened 2024-04-19 12:37 UTC by MikotoMakizuru

プラクティス、ls コマンドを作るオブジェクト指向版の提出物です。

2024-04-26 16:17 UTC, u1tnk requested changes
クラス構成など良いと思います！細かめのところ指摘しました！

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/display_list.rb
> +  def initialize(params)
一瞬paramsにするなら argv で良いかなと思いました。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/display_list.rb
> +    pathname = Pathname('test/fixtures/sample-app')
これは固定パスではなく、実行したパスの方が良いですね。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/display_list.rb
> +    @options[:long_format] ? display_long_format(LongFormat.new(file_paths)) : display_short_format(ShortFormat.new(file_paths))
せっかく LongとShortの二クラス作るなら この場合分けで インスタンス生成して、duck typeを使って共通化したいですね。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/file_info.rb
> +  attr_reader :file_path, :stat
外部公開の必要の無い変数はattr_readerに入れずインスタンス変数で使うようにしましょう。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/long_format.rb
> +      FileInfo.new(file_path, stat)
statはFileInfoクラスしか見る必要が無いので内部で取得する方が良いと思います。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/permission.rb
> +  attr_reader :stat
ここも同様です。

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/file_info.rb
> +    Permission.new(stat).mode
クラス作ってすぐ実行というのはあんまりオブジェクト指向的では無いですが、現場で肥大したクラスを分割するのによくやる手法なので良いと思います  👍

2024-04-26 16:17 UTC, u1tnk commented on 08.ls_object/lib/short_format.rb
> +  def col_count(file_paths)
columnをcolは大差無いので省略しない方が分かりやすいと思います。

2024-04-28 10:26 UTC, MikotoMakizuru commented on 08.ls_object/lib/display_list.rb
> +    @options[:long_format] ? display_long_format(LongFormat.new(file_paths)) : display_short_format(ShortFormat.new(file_paths))
一応修正は行いましたが、方向性があっているかどうか自信がありません。以下のように考え、duck typing を試みました。
1. LongFormat クラス、ShortFormat クラス両方に、display メソッドを作成
2. 三項演算子で、どちらのインスタンスを生成するかを判断する
3. 2 で生成されたインスタンスを `formatted` に代入
4. DisplayList クラスの display メソッドに渡す引数である `formatted` (オブジェクト)は、`formatted.display` が呼び出せることを期待し、それ以外のことは何も気にしない(メソッドが呼び出せれば良い。)

2024-04-28 10:30 UTC, MikotoMakizuru commented on 08.ls_object/lib/display_list.rb
> +    pathname = Pathname('test/fixtures/sample-app')
パス指定がない場合、実行したパス配下のファイルを表示するようにし、パス指定がある場合、指定されたパス配下のファイルを表示するようにしました。

2024-04-28 10:31 UTC, MikotoMakizuru commented on 08.ls_object/lib/file_info.rb
> +  attr_reader :file_path, :stat
インスタンス変数を使うように修正しました。

2024-04-28 10:31 UTC, MikotoMakizuru commented on 08.ls_object/lib/long_format.rb
> +      FileInfo.new(file_path, stat)
stat は FileInfo クラスで取得するようにしました。

2024-04-28 10:32 UTC, MikotoMakizuru commented on 08.ls_object/lib/permission.rb
> +  attr_reader :stat
インスタンス変数を使うように修正しました。

2024-04-28 10:41 UTC, MikotoMakizuru commented on 08.ls_object/lib/file_info.rb
> +    Permission.new(stat).mode
> クラス作ってすぐ実行というのはあんまりオブジェクト指向的では無い

なるほどです！実装中に、FileInfo クラスに mode があることの違和を感じて、Permission クラスを作成し mode のみを切り出した背景がありました。クラスが肥大化していないならこのような実装は避けたいと思います。

2024-04-28 14:16 UTC, u1tnk requested changes

2024-04-28 14:16 UTC, u1tnk commented on 08.ls_object/lib/display_list.rb
> +    formatted = @options[:long_format] ? LongFormat.new(file_paths) : ShortFormat.new(file_paths)
方針は大体大丈夫ですが、
- 変数名とクラス名は formatterにした方で良いですね。基本的にクラス名は名詞ですし、displayメソッドが呼ばれたときにformatするはずですし。
- xxxFormatクラスのdisplayメソッドはformatなどに変更した方が良いですね。displayメソッドは出力までして欲しいので。
- このクラスのdisplayメソッドにはせず、ここでそのまま実行すれば良いと思います。

2024-04-29 14:38 UTC, u1tnk approved these changes

2024-04-29 19:00 UTC, merged